import copy
from typing import List
from collections import defaultdict, deque
from typing import List

from sort_swap_count import sort_swap_count


def count_swaps_unique(list1:List, list2:List, print_error=True) -> int:
    """
    zählen der notwendigen Vertauschungen in der Reihenfolge zwischen 2 Listen
    https://blog.finxter.com/counting-swaps-5-best-ways-to-convert-one-python-list-to-another/
    :param source:
    :param target:
    :return:
    """
    # print("count_swaps", list1, list2, flush=True)
    for i in list1:
        if i not in list2:
            raise Exception("das kann auch nicht: count_swaps")
    if len(set(list1)) != len(set(list2)):
        raise Exception("count_swaps has different lists (no generated by swaps)")
    if list1 == list2:
        return 0
    # doppelte Werte behandeln:
    if len(list1) != len(set(list1)):
        return count_swaps_duplicates(list1, list2, print_error=print_error)

    source = copy.deepcopy(list1)
    target = copy.deepcopy(list2)
    lookup = {val: idx for idx, val in enumerate(target)}
    source = [lookup[v] for v in source]
    swaps = 0
    for i in range(len(source)):
        while source[i] != i:
            # print(source, swaps, target)
            swap_idx = source[i]
            source[i], source[swap_idx] = source[swap_idx], source[i]
            swaps += 1
    return swaps



def count_swaps_duplicates(list1: List, list2: List, print_error=True) -> int:
    if len(set(list1)) != len(set(list2)):
        if print_error:
            raise Exception("count_swaps has different lists (no generated by swaps)")
        return 0

    # Step 1: collect differing elements
    differing_elements = []
    for i in range(len(list1)):
        if list1[i] != list2[i]:
            differing_elements.append((list1[i], list2[i]))

    # Step 2: find inverted pairs and count swaps
    counted = []
    swaps = 0

    remaining_elements = []
    for i in range(len(differing_elements)):
        a1, b1 = differing_elements[i]
        adding_possible = False
        for j in range(i + 1, len(differing_elements)):
            a2, b2 = differing_elements[j]
            if a1 == b2 and b1 == a2 and i not in counted and j not in counted:
                swaps += 1
                counted.append(i)
                counted.append(j)
                adding_possible = True
        if not adding_possible:
            remaining_elements.append(differing_elements[i])
    if len(counted) != len(differing_elements):
        # exchanges within a pair
        return sort_swap_count(array_ist=list1, array_soll=list2)
    return swaps



# testing
assert count_swaps_unique([1, 2, 3], [1, 2, 3]) == 0
assert count_swaps_unique([1, 2, 3], [1, 3, 2]) == 1
assert count_swaps_unique([1, 2, 3], [3, 1, 2]) == 2

assert count_swaps_unique(["a", "b", "c"], ["a", "b", "c"]) == 0
assert count_swaps_unique(["a", "b", "c"], ["a", "c", "b"]) == 1
assert count_swaps_unique(["a", "b", "c"], ["c", "a", "b"]) == 2

#
assert count_swaps_unique(['0', 'a', '2', 'a', 'a', '2', 'a', '0'],
                              ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 0
assert count_swaps_unique(['0', 'a', '2', '0', 'a', '2', 'a', 'a'],
                              ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 1
assert count_swaps_unique(['0', 'a', 'a', '0', 'a', '2', '2', 'a'],
                              ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 2
assert count_swaps_unique(    ['a', 'a', 'a', 'a', '2', '2', '0', '0'],
                              ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 2
assert count_swaps_unique(['a', 'a', 'a', '0', '0', '2', '2', 'a'],
                              ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 3
assert count_swaps_unique(['a', '2', 'a', '0', '0', 'a', '2', 'a'],
                              ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 4
assert count_swaps_unique(    ['0', '0', 'a', '2', 'a', 'a', '2', 'a'],
                              ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 3
assert count_swaps_unique(    [ 'a', '0', '0', 'a', '2', 'a', 'a', '2'],
                              ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 3
assert count_swaps_unique(    ['a', 'a', 'a', 'a', '2', '0', '2', '0'],
                              ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 3
assert count_swaps_unique( ['a', '2', '2', 'a', 'a', '0', '0', 'a'] ,
                        ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 5
assert count_swaps_unique(['a', 'a', '0', '0', '2', 'a', '2', 'a'] ,
                        ['0', 'a', '2', 'a', 'a', '2', 'a', '0']) == 6